apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx-operator
  template:
    metadata:
      labels:
        name: nginx-operator
    spec:
      serviceAccountName: nginx-operator
      containers:
        - name: nginx-operator
          # Replace this with the built image name
          image: aabcoesd/nginx-operator:1.0
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "nginx-operator"
